// ------------------------------- USER INPUT --------------------------------------

	//converting the user try(char) into an int(array)
	void input_to_array(char try[],int num_tab[])//converting user input into int array
		{
			int a,b,c,d;
			int num = atoi(try);//char to int

			a = num /1000;
			b = ( num%1000 ) /100;
			c = (num %100) / 10;
			d = num % 10;

			num_tab[0] = a ;
			num_tab[1] = b ;
			num_tab[2] = c ;
			num_tab[3] = d ;			
		}

	//making sure every digit is unique, else error
	int unique_digits(int num_tab[])
	{
		int a = num_tab[0];
		int b = num_tab[1];
		int c = num_tab[2];
		int d = num_tab[3];

		int testa =0;
		int testb =0;
		int testc =0;
		int testd =0;


		int i = 0;
		for (; i < 4; ++i)
		{
			if (num_tab[i] == a)
			{
				testa = testa+1;
			}
		}

		int j = 0;
		for (; j < 4; ++j)
		{
			if (num_tab[j] == b)
			{
				testb = testb+1;
			}
		}

		int k = 0;
		for (; k < 4; ++k)
		{
			if (num_tab[k] == c)
			{
				testc = testc+1;
			}
		}

		int l = 0;
		for (; l < 4; ++l)
		{
			if (num_tab[l] == d)
			{
				testd = testd+1;
			}
		}


		return testa + testb + testc + testd;
	//end of function
	}
	
	//getting the user try as a char
	void get_try(char try[],int num_tab[])//user input as char
	{
		do
		{
			printf("\tYour try : ");scanf("%s",try);
			input_to_array(try,num_tab);

			if ((strlen(try) != 4)|| (unique_digits(num_tab)!=4))
			{
				error_input();
			}

		} while ( (strlen(try) != 4 )|| (unique_digits(num_tab)!=4) );
	//end of function
	}
	
// ------------------------------- GENERATING RANDOM UNIQE NUMBER ------------------

	void random_number(int numbers[],int random[])//random number generated by the computer
	{
		int a,b,c,d;
		srand((unsigned)time(NULL));


		// unique random a
		a = rand()%10;
		random[0] = numbers[a];
		int i=a;
		for (; i < 10; ++i)
		{
			numbers[i] = numbers[i+1];
		}

		// unique random b
		b = rand()%9;
		random[1] = numbers[b];
		int j=b;
		for (; j < 9; ++j)
		{
			numbers[j] = numbers[j+1];
		}

		// unique random c
		c = rand()%8;
		random[2] = numbers[c];
		int k=c;
		for (; k < 8; ++k)
		{
			numbers[k] = numbers[k+1];
		}

		// unique random d
		d = rand()%7;
		random[3] = numbers[d];
		int l=d;
		for (; l < 7; ++l)
		{
			numbers[l] = numbers[l+1];
		}
	//end of function
	}

// -----------------------------GAME ---------------------------------

	 void hint(int random[])//hint displayed for debuging only
	 {
	  		color(3);
	 		printf("\n\n");
	 		printf("HINT : ");	 	
		 	int i=0;
		 	for (; i < 4; ++i)
		 	{
		 		printf("[ %d ] ",random[i]);
		 	}printf("\n\n");
	 		color(15);
	 }
	 
	 void play(int try[],int random[], int num_tab[],FILE *f)//where magic happens
	 {
	 		system("CLS");
	 		hint(random);
		 	int attempt =0;//number of attempts
		 	int test_bulls;//testing for bulls
		 	int test_cows;//testing for cows
		 	int col =6;



		 	hidden();//header, position(fixed)
		 	printf("\t\t\t\t\tCows   |   Bulls    |  Attempts\n");
	 		 	
		 	do
		 	{	
		 		color(col);	
			 	get_try(try,num_tab);//user try

			 	test_bulls = 0;
		 		test_cows = 0;


		 		int i = 0;
			 	for (; i < 4; ++i)
			 	{
			 		int j=0;
			 		for (; j < 4; ++j)
			 		{
			 			if (num_tab[i] == random[j])
			 			{
			 				if (i == j)
			 				{
			 					test_bulls += 1;
			 				}else{
			 					test_cows += 1;
			 				}
			 			}
			 		}
			 	}

			 	attempt +=1;

			 	printf("\t\t\t\t\t  %d    ",test_cows);
			 	color(15);printf("|");color(col);
			 	printf("      %d     ",test_bulls);
			 	color(15);printf("|");color(col);
			 	printf("     %d\n",attempt);
			 	

			 	col +=1;//setting try color to match the result color, easier to read
			 	if (col ==14)//if color reaches 14 (15 = white) then reset back to 6 
			 	{
			 		col =6;
			 	}


			 } while (test_bulls != 4);

			 if (test_bulls == 4)
			 {
			 	you_win(random);//dsicplaying win message			 	
			 	keep_score(f,attempt);//saving the player's score				
			 }

	//end of play
	 }
	 


	 void get_choice(int *choice)
	 {
	 	printf("\t> ");
	 	scanf("%d",choice);
	 }


// ---------------------------------------------------------------------

main(void)
{
	system("MODE 80,50");//setting the width ans height of the output console

	// variables
		char try[5];//user input(initial)
		int num_tab[5];//array of ints(user input to be used in game)
		int numbers[10]={0,1,2,3,4,5,6,7,8,9};//array containing possible ints to be chosen by pc
		int random[4];//random number generated byt the computer
       
        FILE *f;
		char top_5[5] = {0};//table containing best 5 scores
		int choice = 0;//user's choice

	//functions call	
		random_number(numbers,random);//random by pc
		hint(random);//prints out secret number chosen by PC

		//thses were used for debuging, feel free to delete

		// 		play(try,random,num_tab,f);
		// 		// show_score(f);
		// 		// printf("best score : %d",best_score(f));
		// 		// printf("Last score : %d",last_score(f));	
		// 		// last_score(f);//printing out last score 
		// 		getch();
		// 		//scores_function(f);
		// 		getch();
		// 		rules();

			int pos=1;//selected item's position (default =1 : first item)
			int key=0;//pressed key on the keyboard (up:72/down:80/enter:13)

		do//main menu
		{

			do
			{
			system("CLS");
			printf("\n\n\n");
			color(11);
			printf("\t\t\t\tEL TORO\n\n\n");
			color(15);
			printf("\t--------------------------------------------------------\n\n");

			selected(1,pos);	printf("\t\t\t1 - P L A Y \n\n");		color(15);
			selected(2,pos);	printf("\t\t\t2 - S C O R E S\n\n");	color(15);
			selected(3,pos);	printf("\t\t\t3 - H E L P\n\n");		color(15);
			selected(4,pos);	printf("\t\t\t4 - E X I T\n\n");		color(15);

			printf("\t--------------------------------------------------------\n\n\n");



			key=getch();

			if ( (key==80)&&(pos!=4) )
			{
				pos+=1;
			}else if ((key==72)&&(pos!=1))
			{
				pos-=1;
			}
			
			}while(key != 13);

			//---------------------------------------------------

			if (pos == 1)
			{
				play(try,random,num_tab,f);
				getch();
			}else if (pos ==2)
			{
				scores_function(f);
				getch();
			}else if (pos == 3)
			{
				rules();
				getch();
			}else if (pos == 4)
			{
				exit(1);
			}else{
				color(12);
				printf("\tPlease choose a valid number !\n");
				color(15);
			}


		} while (pos != 4);

}